name: 'LGTM'
description: 'Move fast, break all the things'
author: 'dylanferguson'
inputs:
  token:
    description: >
      GitHub Access Token to create issue comment.
      In many cases, you do not need to prepare yourself. (provided by GitHub Actions)
      Token must have issues:write permission.
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
